version: '3'

services:
  mysql:
    image: 'mysql:8.0.17'
    environment:
      MYSQL_ROOT_PASSWORD: mysql_password
    ports:
      - 3306:3306
    volumes:
      - ./mysql_init:/docker-entrypoint-initdb.d
    restart: unless-stopped
  joupon:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:8080
    environment:
      APP_CONFIG: local
      JOUPON__MYSQL__JDBC_URL: "jdbc:mysql://mysql:3306/joupon?serverTimezone=UTC&characterEncoding=UTF-8&rewriteBatchedStatements=true&cacheServerConfiguration=true&maintainTimeStats=false&useLocalSessionState=true"
      JOUPON__MYSQL__USER: root
      JOUPON__MYSQL__PASSWORD: mysql_password
      JOUPON__INTERNAL_API_KEYS: internal_key_1,internal_key_2
    restart: unless-stopped
    depends_on:
      - mysql
