joupon:
  port: 8080
  host: 0.0.0.0

  mysql:
    jdbcUrl: "jdbc:mysql://localhost:3306/joupon?serverTimezone=UTC&characterEncoding=UTF-8&rewriteBatchedStatements=true&cacheServerConfiguration=true&maintainTimeStats=false&useLocalSessionState=true"
    user: "root"
    password: ""
    maxPoolSize: 5

  internalApiKeys: "internal_api_key1,internal_api_key2"
